### ISSUE TITLE
Wheels for Python 3.8

### ISSUE THREAD

**Issue by ecederstrand** [sbmlteam/python-libsbml#10]
I noticed that wheels for Python 3.8 are missing at https://pypi.org/project/python-libsbml/#files

Can you upload wheels for Python 3.8 for the latest or future releases?

**Comment by fbergmann** [comment]
yes we plan do have a 3.8 release soon, at the latest within a months time. I'll update this item when its done.

**Comment by fbergmann** [comment]
i have updated this repo, and uploaded binary 3.8 wheels to pypi
