### ISSUE TITLE
Is this the repo for python-libsbml on PyPI?

### ISSUE THREAD

**Issue by ecederstrand** [sbmlteam/python-libsbml#11]
I'm a bit confused, because https://pypi.org/project/python-libsbml/ lists version 5.18.0 but this repo has version 5.12.1 in setup.py:

https://github.com/sbmlteam/python-libsbml/blob/0d43ab9e09542f2f8c40a01252bc094ba7584bc5/setup.py#L103

**Comment by fbergmann** [comment]
It is not, it was an experimental project, generated from the original project developed in C++ (as people had problems with dependencies), that is currently still hosted on sourceforge: 

* https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/libsbml/

I hope to update this next week to the same files as on pypi. But I won't find for this until next week.
