### ISSUE TITLE
Compile a ASTNode

### ISSUE THREAD

**Issue by tonyxwz** [sbmlteam/python-libsbml#14]
In my project, I need to compute the flux of a reaction.
This can be done now by

```python
formula = compile(kineticlaw.formula, "<string>", "eval")
# then
eval(formula, {}, context)
```
This is ok, but might affect the speed of the program. Is there any other way to do this? I just couldn't find it in the python api guide. 

Thanks.

**Comment by mhucka** [comment]
Hi – Indeed, this is one way to do it. As you no doubt realize, interpreting the mathematical expressions becomes a bottleneck in simulations. There are off-the-shelf libraries and solvers that implement faster methods for SBML models, and I can try to point you to some. Can you explain just a little bit more about your situation? In particular, (1) are you using the flux balance constraints package in SBML or just plain core SBML, (2) which Level/Version of SBML are you using, and (3) in your case, is it an option to call an external library, or must it all be pure Python?

**Comment by tonyxwz** [comment]
Hi @mhucka , thanks for you reply

A bit more about my situation. My project is to develop a toolbox to improve the parameters in a SBML model. It involves dividing the simulation into small steps and optimize the parameters in each iteration.

1. I am not using the flux balance constraints packages. My model is a ODE model and I need to calculate the fluxed to calculate the derivatives in the system of ODE. 
2. I am using the latest python-libsbml. But the model document is at Level 2. More specifically, I am testing on [BioModels: 380 by Smallbone et al.](https://www.ebi.ac.uk/biomodels/BIOMD0000000380).
3. I don't mind at all using an external library. But I prefer it at least can be called from python using `subprocess` and specify the parameters, since the parameter need to be changed between each iteration.
4. The parameters I need to optimize are the ones in the kinetic law under reaction node, not only those under model node. So it might be important to be able to specify which `Vmax`, if there are many `Vmax`s in different reactions.

Please point me to any library you come up with. Thanks again.

**Comment by mhucka** [comment]
Thanks for all those details! In this case, the following options are what come to mind first, in no particular order:

* [Tellurium](https://tellurium.readthedocs.io/en/latest/) provides a Python-based environment with a lot of functionality, and it uses a library called [libRoadRunner](https://libroadrunner.readthedocs.io/en/latest/) that could be invoked independently

* The [Python interface to COPASI](https://pypi.org/project/python-copasi/)  – COPASI has a [variety of ODE solvers built in](http://copasi.org/Support/Features/) as well as built-in optimization facilities

* [CBMPy](http://cbmpy.sourceforge.net) interfaces to ODE solver libraries and provides another option

The above are pretty complete systems with a lot of documentation, but they may or may not have the capabilities you need to interact with the parameters in the kinetic laws. If you are able to take a look and if none of the above work out, then if you can let us _how_ they don't suffice, I'll try to think of more options!

**Comment by tonyxwz** [comment]
I used COPASI in my university, but only with GUI. I will checkout libRoadRunner, it seems more promising. I will update here once I finished this project. Thanks!
