### ISSUE TITLE
Linker not found on Windows

### ISSUE THREAD

**Issue by Midnighter** [sbmlteam/python-libsbml#15]
Hi,

I recently had a Windows user of cobrapy [report a build error](https://groups.google.com/d/msg/cobra-pie/NSJ8dIBJ8Lk/vDH9OZHFBwAJ) of python-libsbml-experimental.

In order to improve the experience for Windows users I am now trying to add a python-libsbml-experimental package on conda-forge. However, I'm experiencing the same missing `link.exe` error in the [Windows pipeline](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=123927&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=78a0099b-3f13-5ae9-c1f0-24f71d1eac20&l=3686).

Do you have any experience with Windows builds that could help here? Could it be that the configuration detected by the `setup.py` script is somehow wrong?

**Comment by Midnighter** [comment]
I actually found a clue [in this thread](https://travis-ci.community/t/msvc-link-exe-not-found/6022) (also mentioning libsbml). It appears that the last command linking all the compiled objects is too long which triggers the unhelpful message `'link.exe' failed: No such file or directory`. Probably because parts of a path were cut off.

The solution is to use an auxiliary file as described in the [MSVC documentation](https://docs.microsoft.com/en-us/cpp/build/reference/linking?view=vs-2019#link-command-files). I'm not sure what is more convenient:

1. Possibly hacking the `setup.py` to use a file for the link command.
2. Use cmake in combination with [ninja](https://ninja-build.org/) or [NMAKE](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-reference?view=vs-2019) that automatically handle this.

I don't know how the current Windows wheels are being built. Maybe you, @skeating,  have some experience with this?

**Comment by Midnighter** [comment]
I just checked and (quite possibly due to using a conda environment which increases the length of some printed paths) the `link.exe` command is indeed 5245 characters long which is over the allowed limit on Windows.

**Comment by fbergmann** [comment]
Indeed, windows binaries we produce and distribute are not generated using the setup.py script, but rather we use the normal CMake setup of libSBML. As mentioned before, this project here is only there out of convenience, for those systems where we could not easily generate binaries for.

**Comment by Midnighter** [comment]
If I want to do that, I grab the code from here https://sourceforge.net/p/sbml/code/HEAD/tree/ ?

**Comment by fbergmann** [comment]
Just to update on this, using a custom build extension, that calls setup tools, i have been able to build python-libsbml directly using setuptools on all platforms. I've committed what i have now to the 

<https://github.com/sbmlteam/python-libsbml/tree/setuptools_cmake>

branch. This allows us of not needing to duplicate all the sources and instead makes it possible to use the normal libSBML build process. I still need to make some further changes (post processing of the SWIG wrappers for python 3 is missing, and understanding how travis does the build setup, maybe i pull in libsbml  / dependency project in as submodule). But might not have time to work on this until the end of the week.

**Comment by Midnighter** [comment]
I'll check out your branch and see if I can suggest any enhancements.

**Comment by Midnighter** [comment]
Yeah, indeed. If there was a git clone of the SVN repo, the sources could be added with git subtree or git submodule. Then python-libsbml would just be the Python setup code around that. Sounds like a really good idea to me.
