### ISSUE TITLE
Wheels for Python 3.8 (python-libsbml-experimental)

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/python-libsbml#17]
I all, we are using python-libsbml-experimental in cobrapy and some users require python 3.8. Would it be possible to also provide the py3.8 wheels for python-libsbml-experimental.
(see discussion in https://github.com/opencobra/cobrapy/pull/933#issuecomment-593921511)

Best Matthias

**Comment by ecederstrand** [comment]
Ping @fbergmann  ?

**Comment by fbergmann** [comment]
@ecederstrand  please have a look now ... @bgoli released new python-libsbml-experimental binaries. Please let us know if this solves the issue

**Comment by ecederstrand** [comment]
Looks good. Thanks!
