### ISSUE TITLE
Documentation for adding the sbml-qual extension?

### ISSUE THREAD

**Issue by djinnome** [sbmlteam/python-libsbml#19]
Hi folks,

I am trying to read an sbml-qual file in https://git-r3lab.uni.lu/covid/models/-/tree/master/Executable%20Modules

What is the magic incantation to enable the qual extension?

If I do this:

```python
>>> import libsbml
>>> r = libsbml.SBMLReader()
>>> d = r.readSBML('Apoptosis_qual.sbml')
>>> m = d.getModel()
>>> m.getNumSpecies(), m.getNumReactions()
```
I get this: 

```
(0,0)
```

**Comment by djinnome** [comment]
I tried this:

```python
>>> m.enablePackage(pkgURI='http://www.sbml.org/sbml/level3/version1/qual/version1',
                pkgPrefix='qual',flag=True) == libsbml.LIBSBML_OPERATION_SUCCESS\
True            
```

I then tried to install `python-libsbml-experimental`, but that still didn't do the trick.

**Comment by fbergmann** [comment]
Hello Jeremy 

This is pretty much working as intended. The Qual package group decided not to work with the SBML species and reaction classes, and instead to create their own versions. To access them, you'd first get the qual plugin from the model object, and then interrogate that one: 

    import libsbml
    doc = libsbml.readSBMLFromFile('Executable Modules_Apoptosis_qual.sbml')
    m = doc.getModel()
    qual = m.getPlugin('qual')
    print ('qual species: {0}, qual transitions: {1}'.format(
      qual.getNumQualitativeSpecies(),
      qual.getNumTransitions()))

**Comment by djinnome** [comment]
Thank you @fbergmann this is exactly the documentation I was hoping for.

I see now that `m.getPlugin()` the canonical way to get SBML Layouts and FBC constraints, too!

Sincerely,

Jeremy
