### ISSUE TITLE
Need a better way to keep the version number updated

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/python-libsbml#2]
The file PKG-INFO currently has a hard-coded libSBML version number (which is currently listed as 5.12.1).  I'm concerned it will be too easy for the maintainers to update the version when issuing a new release. 

On approach might be to create a script that is run as part of the release procedure; the script could use sed or something similar to update the version number automatically.

**Comment by Midnighter** [comment]
On the Python-side you can use tools like bumpversion or versioneer for just that task.

**Comment by fbergmann** [comment]
this is not an issue, as the PKG-INFO file is automatically generated out of the setup.py script i n which the version is automatically updated by cmake before creating the source package

**Comment by Midnighter** [comment]
At the moment you are committing the PKG-INFO file to the repository. I think that should be removed since it is auto-generated as you say?

**Comment by mhucka** [comment]
@fbergmann I think @Midnighter is right.

**Comment by fbergmann** [comment]
Commits 

c652546476c5206303f96ed0e38516bdac11877d and
7b543ac7f2a5fca1c0cebcfacfa98ec13238b2ef

(while sadly referencing the wrong issue), should take care of this.
