### ISSUE TITLE
Call the project 'libsbml' on pypi

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/python-libsbml#21]
The standard way to install something from pypi is to use pip:

pip install libsbml

However, since we've called the project 'python-libsbml', this doesn't work.  Instead, users have to type:

pip install python-libsbml

The project on pypi.org should just be 'libsbml', not 'python-libsbml'.  I mean, it's already on pypi.

Also, since we've merged libsbml and libsbml-experimental, I would vote that we just have a single pypi project called 'libsbml' with all packages enabled.

**Comment by Midnighter** [comment]
While I agree that it would be nice to simply run `pip install libsbml`, it is actually a very common pattern to have the prefix `python-` in the installable package name but importing it under the shortened name.

**Comment by luciansmith** [comment]
Did it used to be more common than it is now?  Because I've not seen it before.  I did a search for 'a' on pypi.org, and of the first 500 entries, exactly two of them had that pattern.

**Comment by Midnighter** [comment]
Okay, not as often as I thought (~ 1.4%) but there are some popular examples. Ones that I have used myself:

* python-dateutil
* python-jose
* python-multipart
* python-dotenv
* python-slugify
* python-editor
* python-http-client
* python-levenshtein

```python
import httpx
from bs4 import BeautifulSoup


response = httpx.get("https://pypi.org/simple")
response.raise_for_status()

soup = BeautifulSoup(response.text)

package_names = [link.text for link in soup.find_all("a")]
len(package_names)
# 258240

sum(1 for name in package_names if name.startswith("python-") or name.endswith("-python"))
# 3628
```

**Comment by luciansmith** [comment]
OK, fair enough.  And a colleague tells me that the practice is more common for projects that have a life outside of python, too.
