### ISSUE TITLE
Release an experimental version of each version of the main release

### ISSUE THREAD

**Issue by jonrkarr** [sbmlteam/python-libsbml#28]
I recently realized that there's a second release which has support for the draft packages enabled.

Currently python-libsbml-experimental is released as 5.19.0, but python-libsbml is at 5.19.3.

To make it easier to manage the installation of python-libsbml-experimental, I think it would be helpful to release a new version each time a new version of the main package is released. For example, this would enable me to (1) install simulation tools which require libsbml, (2) detect which version of libsbml pip/pipenv determined was compatible with those tools, and (3) install the corresponding experimental release of that version.

@luciansmith explained that the experimental version of 5.19.3 would be the same as 5.19.0 (the changes from 5.19.0-5.19.3 don't impact the experimental release). Nevertheless, I think additional releases of the experimental version would help me manage my Python environment.

**Comment by fbergmann** [comment]
I've just released a 5.19.3 version for experimental as well. And i agree, i'll be sure to keep them in sync from now on.

**Comment by jonrkarr** [comment]
Thanks!
