### ISSUE TITLE
Need to document process for updating copy of libSBML

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/python-libsbml#3]
We should document the method for updating the copy of the libSBML Python bindings in here. Currently, it is not immediately obvious how that's supposed to be done for new releases.

**Comment by Midnighter** [comment]
Could you even automate it?

**Comment by fbergmann** [comment]
While we could create an action that would be triggered on release of libSBML that would update the submodule, there are actually still some manual steps to be performed (updating the conda feedstocks, ensuring the binaries are built, creating arm linux binaries) that we all want to finish at the same time. so for now I don't see an advantage for automating just this part of it.
