### ISSUE TITLE
Wheels for Python 3.11

### ISSUE THREAD

**Issue by dweindl** [sbmlteam/python-libsbml#30]
Hi, as Python3.11 was released a couple of days ago, it would be great to have python-libsbml wheels for Python3.11 on PyPI. Thanks :)

**Comment by fbergmann** [comment]
will do .. thanks for letting me know.

**Comment by fbergmann** [comment]
I've now added 3.11 wheels to the 5.19.7 release

**Comment by dweindl** [comment]
Thanks, Frank! It works.

**Comment by fbergmann** [comment]
awesome
