### ISSUE TITLE
missing source tarball on PyPI for recent versions

### ISSUE THREAD

**Issue by boegel** [sbmlteam/python-libsbml#31]
Is there a reason why the source tarball for `python-libsbml` is no longer available through PyPI like it used to be (see https://pypi.org/project/python-libsbml/5.19.2/#files for example)?

Is the source tarball that is available via GitHub (for example https://github.com/sbmlteam/python-libsbml/releases/download/v5.19.7/python-libsbml-5.19.7.tar.gz) equivalent?

**Comment by fbergmann** [comment]
I attached it to the github release, but had not uploaded it to pypi. I will upload it now, until it is up you can use the one from the release. That is also what we use for the conda forge builds: 

<https://github.com/sbmlteam/python-libsbml/releases/tag/v5.19.7>

**Comment by fbergmann** [comment]
should now be up on

<https://pypi.org/project/python-libsbml/5.19.7/#files>

**Comment by boegel** [comment]
Thanks a lot for the quick fix!
