### ISSUE TITLE
How to valid an SBML file via the python API or how to distinguish the errors and warnings via python API

### ISSUE THREAD

**Issue by SunnyXu** [sbmlteam/python-libsbml#37]
Hello,
I am using the python API of libSBML to judge whether there is an error of an SBML file using the function getNumErrors() != 0 (https://github.com/SunnyXu/SBMLDiagrams/blob/main/SBMLDiagrams/processSBML.py#L291). However, the warning error also contributes to the number of errors, which seems to be different from the validator online (https://synonym.caltech.edu/validator_servlet/). Because a warning on the validator website does not end up with an invalid SBML file. 
Therefore, is there a better way to judge whether it is a valid SBML files via the python API of libSBML? Or is it possible to have an additional API function like getNumWarnings()?  Please let me know. Thanks in advance.

**Comment by fbergmann** [comment]
Hello Jin, 

you can pass along a severity you are interested in in `getNumErrors`, that way you can filter only for critical things: 

```python
num_errors = document.getNumErrors(libsbml.LIBSBML_SEV_ERROR)
```

cheers

**Comment by SunnyXu** [comment]
Thanks, Frank.
