### ISSUE TITLE
x86_64 wheels for Python 3.12

### ISSUE THREAD

**Issue by dweindl** [sbmlteam/python-libsbml#38]
Hi, the latest libsbml on pypi has only python3.12 wheels for aarch64 (https://pypi.org/project/python-libsbml/5.20.2/#files) . It would be great if you could also ship x86_64 wheels compatible with python3.12.

**Comment by fbergmann** [comment]
Unfortunately the cibw build fails for 3.12, looking into that. Until then you could grab the binary from conda-forge: 

<https://anaconda.org/conda-forge/python-libsbml/files>

**Comment by fbergmann** [comment]
took a while, but the 3.12 packages are now on pypi ... experimental ones will be there in the morning.

**Comment by dweindl** [comment]
Thanks Frank, it works!
