### ISSUE TITLE
Python 3.6 wheels

### ISSUE THREAD

**Issue by Midnighter** [sbmlteam/python-libsbml#5]
On PyPi there are currently (5.15.0) only Python 3.6 wheels for Windows not for Linux. Can that be fixed?

**Comment by fbergmann** [comment]
i've updated the many linux container we use to build the libsbml wheels. that ought to support 3.6 once the build completes i will upload the 3.6 wheels. I'll update this entry once this is done.

**Comment by Midnighter** [comment]
Awesome!

**Comment by fbergmann** [comment]
the python 3.6 linux binaries are now available from pypi, so i'm closing this. thanks for letting us know
