### ISSUE TITLE
Groups in libSBML

### ISSUE THREAD

**Issue by silviamorins** [sbmlteam/python-libsbml#6]
Hi,

I hope this is the right place to ask: I'm struggling trying to add the reaction groups to my SBML model I built with COBRApy, which does not have this function. I looked up for an example on the website and I found it under: http://sbml.org/Software/libSBML/5.13.0/docs//python-api/libsbml-python-example-files.html#package-groups-examples.

However, in this page the file "groups_example1.py" is not linked to anything. Is there a way to have it back? This file, or any other help, I'm looking of what I think is a really simple function...

**Comment by fbergmann** [comment]
Hello, 

the best way to ask any questions about interoperating with libsbml is the discussion group here: 

https://groups.google.com/forum/#!forum/sbml-interoperability

To answer your question, if you are looking for the example files, we have them in our sourceforge repository, here: 

https://sourceforge.net/p/sbml/code/HEAD/tree/trunk/libsbml/examples/python/groups/

best
Frank

**Comment by mhucka** [comment]
Hi @silviamorins – thanks for reporting the issue. As it happens, the purpose of this particular GitHub repository is for creating the libSBML python library, but it is not for libSBML per se; the libSBML repo is still in SourceForge at https://sourceforge.net/p/sbml/libsbml/.  We do put a link to the bug reporting system on the libSBML home page (which is at http://sbml.org/Software/libSBML ) but I guess we don't make it clear enough in other places. Could you let us know what might have helped in this situation?

Also, a side note: 5.13 is a relatively old version of libSBML. Is there any chance you can update to 5.17? It has a number of fixes that are significant, including to Groups and FBC, which might be relevant to your work.

**Comment by silviamorins** [comment]
Hi,

thank you both for your answers. I guess it was more my fault - I looked here in github for a repository before having a deep look into the website.

Thank you for pointing out about the update!
